modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/mrbysco/forcecraft"
license="MIT"

[[mods]]
modId="randomdecorativethings"
version="${file.jarVersion}"
displayName="Random Decorative Things"
displayURL="https://www.curseforge.com/minecraft/mc-mods/forcecraft"
authors="Mrbysco"
description='''
Some random decorative blocks (maybe items)
'''