modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/Random-Decorative-Things/issues"
license="MIT"

[[mods]]
modId="randomdecorativethings"
version="${file.jarVersion}"
displayName="Random Decorative Things"
displayURL="https://www.curseforge.com/minecraft/mc-mods/random-decorative-things"
authors="Mrbysco"
description='''
Some random decorative blocks (maybe items)
'''
[[dependencies.randomdecorativethings]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"