modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Random-Decorative-Things/issues"
license="MIT"

[[mods]]
modId="randomdecorativethings"
version="${file.jarVersion}"
displayName="Random Decorative Things"
displayURL="https://www.curseforge.com/minecraft/mc-mods/random-decorative-things"
authors="Mrbysco"
description='''
Some random decorative blocks (maybe items)
'''
[[dependencies.randomdecorativethings]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.randomdecorativethings]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"